apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: li4vn5hau-dotnet-basic-gitops-repository
spec:
  url: https://github.com/tnevrlka-rhtap/li4vn5hau-dotnet-basic-gitops