apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: li4vn5hau-dotnet-basic 
  janus-idp.io/tekton: li4vn5hau-dotnet-basic
  backstage.io/kubernetes-id: li4vn5hau-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: li4vn5hau-dotnet-basic
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml